config/routes.rb
Rails.application.routes.draw do
  resources :lessons

  devise_for :users
  root 'lessons#index'

  get 'about' => "pages#about"

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	has_many :users

	mount_uploader :video, VideoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def show
  end

  def new
    @lesson = current_user.lessons.build
  end

  def edit
  end

  def create
    @lesson = current_user.lessons.build(lesson_params)
      if @lesson.save
        redirect_to @lesson, notice: 'Lesson was successfully created.'
      else
        render action: 'new'
      end
  end

  def update
    if @lesson.update(lesson_params)
        redirect_to @lesson, notice: 'Lesson was successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
      @lesson.destroy
      redirect_to lessons_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def correct_user
      @lesson = current_user.lessons.find_by(id: params[:id])
      redirect_to lessons_path, notice: "Not authorized to edit this lesson" if @lesson.nil?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :description, :video)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Bright</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bright</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
</head>
<body>
	
  	<%= render 'layouts/header' %>
     <div class="container">
          <%= yield %>
     </div>

</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

  <%=f.file_field :video%>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<%= render 'pages/home' if !user_signed_in? %>

<!-- <div id="lessons" class="transitions-enabled">
<h1>Listing lessons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.description %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<%= link_to 'New Lesson', new_lesson_path %> -->

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<h1>
  <strong><%= @lesson.title %></strong>
</h1>
</div>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>




<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>

app/views/pages/_home.html.erb
<div class="jumbotron center">
     <h1>Welcome to Bright</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/pages/about.html.erb
<h1>Bright Learning: the Private school alternative to K - 12</h1>
<h3>What is Bright Learning?</h3>
<p>Bright Learning is a subsidiary of Inquisicorp (Inquisicorp software division). Its sole purpose is to teach children faster and better than any other educator on the planet.</p>
<h3>Sounds awesome. . . but how does it work?</h3>
<p>So far we have a math program that pulls from some of the very best modern principles for speed learning:</p>
<ol><li>CrossFit style math to add in an interesting and extremely motivating framework to the more "traditional" approach.</li>
	<li>Math grounded in the real world. The single biggest question that math teachers hear day in and day out from kids failing at math: "Why do I have to learn this? I just don't see the point." By grounding math principles with the things around them your child will instantly "get it" and build more long term neurological connections. Text books. . . its time to take a back seat.</li>
	<li>Our smart algorithm will drip feed the problems based around the concepts that your student needs a refresher on. . . as they need a refresher (and not AFTER some test tells them they need to).</li>
	<li>Real time, trackable results you can see.</li>
</ol>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to Bright Learning</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>